steps:
 # Pull image if exists
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
   - '-c'
   - docker pull gcr.io/$PROJECT_ID/firebase:latest || exit 0
 # Build image with cache
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 
     'build', 
     '-t', 'gcr.io/$PROJECT_ID/firebase:latest',
     '--cache-from', 'gcr.io/$PROJECT_ID/firebase:latest',
     '.'
   ]
   env: [
      'commit=$SHORT_SHA',
      'firetoken=$$FIREBASE_TOKEN'
   ]
   secretEnv: [
      'FIREBASE_TOKEN'
   ]
images: ['gcr.io/$PROJECT_ID/firebase:latest']
secrets:
- kmsKeyName: projects/iowine-cloud/locations/global/keyRings/firebase/cryptoKeys/FIREBASE_DEPLOY_TOKEN
  secretEnv:
    FIREBASE_TOKEN: CiQAwVhgiBMkMCnQ6rX3kldlOKW7Gii97+TEIPnNvYhFmBLI+CUSVgAGU6JrDS7bu5grLfa3BHT42cuJoLyaFufC9xnQgRwkCvgZ9flT6hQv1OlG+xZKYp/WBTVuB2SjgeJ9C9/GxMDGw+4kV6p6Gbv1vKO+Wqb+L90IKysa