steps:
 # Pull image if exists
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
   - '-c'
   - docker pull gcr.io/$PROJECT_ID/$_IMAGE:latest || exit 0
 # Build image with cache
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/$_IMAGE:latest',
    '--cache-from', 'gcr.io/$PROJECT_ID/$_IMAGE:latest',
    '--build-arg', 
    'firetoken=$_FIRETOKEN',
    'commit=$SHORT_SHA',
    '.'
   ]
images: ['gcr.io/$PROJECT_ID/$_IMAGE:latest']
