steps:
 # Pull image if exists
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
   - '-c'
   - docker pull gcr.io/$PROJECT_ID/firebase:latest || exit 0
 # Build image with cache
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 
    'build', '-t', 'gcr.io/$PROJECT_ID/firebase:latest',
    '--cache-from', 'gcr.io/$PROJECT_ID/firebase:latest',
    '--build-arg', 'firetoken=$$FIREBASE_TOKEN',
    '.'
   ]
   env: [
    'commit=$SHORT_SHA'
   ]
   secretEnv: [
    'FIREBASE_TOKEN'
   ]
images: ['gcr.io/$PROJECT_ID/firebase:latest']
secrets:
- kmsKeyName: projects/iowine-cloud/locations/global/keyRings/firebase/cryptoKeys/FIREBASE_DEPLOY_TOKEN
  secretEnv:
    FIREBASE_TOKEN: |-
     CiQAwVhgiFVf1yAQ5npEEticVA2yhMJ/Tirw/+rty/xxUFsX3YwSVgAGU6JrBtB7mbFDeUBhOol4
     YGpt8x+z4ceuGNLInoeCRzbUaRBGtbwhHsfshPGD5GCPOUh5FLe2k/ddCfKiH/Cgd661iZWzBGXb
     TomnNFQTH9pTN7DB